#!/bin/bash

if [[ ! -d ~/.local/firefox ]] ; then
    set -o pipefail
    curdir="$(pwd)"
    cd ~/.local
    OS=linux64
    LANGPACK=""
    [[ "$LANG" == "tr_TR.UTF-8" ]] && LANGPACK="tr"
    [[ "$(uname -m)" == "i686" ]] && OS=linux
    wget "https://download.mozilla.org/?product=firefox-latest-ssl&os=${OS}&lang=${LANGPACK}" -O firefox.tar.bz2 2>&1 | \
    sed -u 's/^[a-zA-Z\-].*//; s/.* \{1,2\}\([0-9]\{1,3\}\)%.*/\1\n#Downloading... \1%/; s/^20[0-9][0-9].*/#Done./' | \
   (
for i in {1..100}; do
    echo $i
    sleep 0.1
done
) | zenity --progress --title="Firefox is being installed" --text="Please wait..." --percentage=0
    tar -xf firefox.tar.bz2
    rm -f firefox.tar.bz2
    cd "$curdir"
fi
exec ~/.local/firefox/firefox $@
